export {default as Hed} from './Hed'
export {default as Img} from './Img'
export {default as Nav} from './Nav'
export {default as Home} from './Home'
export {default as Search} from './Search'
export {default as Popular} from './Popular'
export {default as Grid} from './Grid'
export {default as LoadMorebtn} from './LoadMorebtn'
export {default as Moviepage} from './Moviepage'
export {default as PopUp } from './PopUP'
export {default as Actor } from './Actor'